### ISSUE TITLE
Channels Layers

### ISSUE THREAD

**Issue by mgale456** [uiuc-mrdc/cogs#12]
We need the judging screens to receive the updated time/score from the server even from updates from other judges. At a glance, Django Channels Layers seem to be a good way to do this.

Right now the websocket is purely between the one instance of the judging page and the server. It won't see any responses from the server initiated by another judge. 

@lpulley Looks like we may need to install redis. Are you familiar with it at all?

**Comment by lpulley** [comment]
I'm not at all familiar with redis. I'm sure we can just whip it together over break.

**Comment by lpulley** [comment]
@mgale456 Have you been doing anything with this? I'd forgotten about this part and it's pretty important. I will not have any time this upcoming weekend but I will have a good amount of time over spring break so if we can have some Discord meetings that week, that would be stellar.

**Comment by mgale456** [comment]
I have this working in a preliminary form on `judging-page-fixes`. Right now, every time a standardButton is pressed, Django calculates the score of that team, and broadcasts it to a group names `judges`

Things that still need to be ironed out:

1. [x] I think the IP in `settings.py` under `CHANNEL_LAYERS` is specific to me (maybe). @lpulley please use Docker network magic to fix that. `localhost` didn't work, so I used the IP that django saw my web browser connecting from
2. [x] All judges are in the same group regardless of what game they are looking at. I want this to be game-specific
3. [x] how we display scores on the judging page
4. [x] other communications that need to go out to more than one client (game start, game end, game pause, etc.

**Comment by mgale456** [comment]
that IP configuration for `CHANNEL_LAYERS` is definitely bad. It just changed on me during development when I restarted the containers.

**Comment by mgale456** [comment]
Fixed the Redis IP issue. Channels is fully implemented with no issues afaik.

**Comment by lpulley** [comment]
I've been doing a lot of work with Django Channels so I'm curious to take another stab at this and see if we missed anything.

**Comment by mgale456** [comment]
I read the documentation for it pretty well, and I'm pretty sure I'm handling stuff inside of Channels correctly. However the more overarching best practices like REST APIs for similar purposes to what I implemented over websocket may need to change. I'm curious if you find anything to improve, aside from all of my custom non-documented message structures..... lol

**Comment by lpulley** [comment]
Having to come up with your own message structures is a great reason why using the API for everything possible is nice.

**Comment by mgale456** [comment]
Well, it uses JSON. I just meant the fields, and how some of the requests may use the same field in different ways. Most of that should be about the same with a REST API, I think. Although maybe the "Web browsable API" feature will kinda documents some things for us in a nice way, and we'll be a bit more organized with the structure of it all.
