### ISSUE TITLE
Database queries for scoring

### ISSUE THREAD

**Issue by mgale456** [uiuc-mrdc/cogs#18]
Need to double check Django is caching the queries as I am wanting. Hopefully it should only hit the database once. Then we can merge it back in

I was testing by putting this in the vies file under `index`:
`print(GameParticipant.objects.get(pk=1).score())`

Note that this just prints the score for the Lion team.

**Comment by lpulley** [comment]
Can you be more specific? Just saw this and I'm not sure what the issue/enhancement is.

**Comment by mgale456** [comment]
In addition to making the scoring work in the first place, I am trying to optimize the queries to minimize database hits.

I'm using these two new lines in `docker-compose.yml` to get the logs from the mariadb container, and triggering the scoring method as mentioned in this issue by modifying `views.py`:
```
    command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
    volumes:
      - ./logs:/var/log/mysql
```

A good example of this type of optimization is in [this commit](https://github.com/uiuc-mrdc/cogs/commit/d0da44b94c327ee59315dcb7a429b15af6302bb7) in judging-page-fixes which saves 5 database queries. You can test it by uncommenting the other line, since I left it in as an example. It is using [this part of Django's database optimization guide](https://docs.djangoproject.com/en/3.0/topics/db/optimization/#retrieve-everything-at-once-if-you-know-you-will-need-it)


Answering this issue, though:
In the end, the caching of the queries does not work as I thought it might. Since the scoring calculations uses a lot of queries with very similar conditions (where team_id = # AND game_id=#), I was hoping that I could cache that, and then run all of the action-specific queries from that table or something. According to [this thread](https://stackoverflow.com/questions/45980602/django-is-it-possible-to-perform-queries-on-a-cached-queryset-instead-of-queryi), we could do that in Python, but it might end up slower anyways, since databases are so well optimized. 

I also looked through some Mariadb caching documentation, and it didn't seem like it had this sort of thing either.

So in the end, I think it is pretty good as it is now. I can probably close this issue, and then *the only issue remaining with the Scoring branch* is the multiplier problem with the counters mentioned in #10. Then we can merge it into master.
